import Link from "next/link";
import { Manrope } from "next/font/google";
import { BrandLogo } from "@/components/BrandLogo";

const manrope = Manrope({
  subsets: ["latin"]
});

export default function TermsPage() {
  return (
    <main className={`${manrope.className} min-h-screen bg-card text-foreground`}>
      <nav className="border-b border-border bg-card">
        <div className="mx-auto flex h-20 max-w-6xl items-center px-6 sm:px-8">
          <Link href="/" className="inline-flex items-center gap-3">
            <BrandLogo size="sm" showWordmark={false} />
            <span className="text-2xl font-bold tracking-tight text-foreground">SnapQuote</span>
          </Link>
        </div>
      </nav>

      <div className="mx-auto max-w-4xl px-6 py-16 sm:px-8">
        <p className="text-sm font-medium text-muted-foreground">Last updated: March 2026</p>
        <h1 className="mt-4 text-4xl font-semibold tracking-tight text-foreground">
          Terms of Service
        </h1>

        <div className="mt-10 space-y-10 text-[15px] leading-8 text-slate-700">
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By using SnapQuote you agree to these terms. If you do not agree, do not use
              the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
            <p>
              SnapQuote is a SaaS platform that provides AI-powered job estimating and lead
              management tools for outdoor service contractors.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">3. Account Responsibilities</h2>
            <p>You must provide accurate information when creating an account.</p>
            <p>You are responsible for maintaining the security of your account.</p>
            <p>You must be 18 or older to use SnapQuote.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">4. Credits and Billing</h2>
            <p>SnapQuote operates on a credit-based system.</p>
            <p>Monthly credits reset on your billing anniversary date and do not roll over.</p>
            <p>Bonus credits purchased separately never expire.</p>
            <p>
              All payments are processed by Stripe and are non-refundable except as required
              by law.
            </p>
            <p>Plan downgrades take effect at the end of the current billing period.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">5. Acceptable Use</h2>
            <p>You agree not to use SnapQuote for any unlawful purpose.</p>
            <p>You agree not to attempt to reverse engineer or exploit the platform.</p>
            <p>You agree not to spam or harass customers through the platform.</p>
            <p>You agree not to submit false or misleading information.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">6. AI-Generated Estimates</h2>
            <p>
              Estimates generated by SnapQuote&apos;s AI are approximations only and should
              not be treated as final estimates. SnapQuote is not responsible for discrepancies
              between AI estimates and actual job costs.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">7. Intellectual Property</h2>
            <p>
              SnapQuote and its content are owned by SnapQuote. You retain ownership of
              content you submit.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">8. Limitation of Liability</h2>
            <p>
              SnapQuote is provided &quot;as is.&quot; We are not liable for any indirect,
              incidental, or consequential damages arising from your use of the service. Our
              total liability shall not exceed the amount you paid us in the past 12 months.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">10. Governing Law</h2>
            <p>These terms are governed by the laws of the State of California.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">11. Changes to Terms</h2>
            <p>
              We may update these terms at any time. Continued use of the service constitutes
              acceptance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">12. Contact</h2>
            <p>
              <a
                href="mailto:support@snapquote.us"
                className="font-medium text-primary hover:text-primary/90"
              >
                support@snapquote.us
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
